# Generated by Django 4.2 on 2024-08-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('acceleration', models.FloatField()),
                ('velocity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_position_x', models.FloatField(blank=True, default=None, null=True)),
                ('actual_position_y', models.FloatField(blank=True, default=None, null=True)),
                ('actual_position_z', models.FloatField(blank=True, default=None, null=True)),
                ('actual_position_a', models.FloatField(blank=True, default=None, null=True)),
                ('actual_position_c', models.FloatField(blank=True, default=None, null=True)),
                ('distance_to_go_x', models.FloatField(blank=True, default=None, null=True)),
                ('distance_to_go_y', models.FloatField(blank=True, default=None, null=True)),
                ('distance_to_go_z', models.FloatField(blank=True, default=None, null=True)),
                ('distance_to_go_a', models.FloatField(blank=True, default=None, null=True)),
                ('distance_to_go_c', models.FloatField(blank=True, default=None, null=True)),
                ('homed_x', models.BooleanField()),
                ('homed_y', models.BooleanField()),
                ('homed_z', models.BooleanField()),
                ('homed_a', models.BooleanField()),
                ('homed_c', models.BooleanField()),
                ('tool_offset_x', models.FloatField(blank=True, default=None, null=True)),
                ('tool_offset_y', models.FloatField(blank=True, default=None, null=True)),
                ('tool_offset_z', models.FloatField(blank=True, default=None, null=True)),
                ('tool_offset_a', models.FloatField(blank=True, default=None, null=True)),
                ('tool_offset_c', models.FloatField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_data', to='machines_app.machine')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines_app.user')),
            ],
        ),
    ]
